name: release
run-name: "Release ${{ github.ref_name }}"

on:
  push:
    tags:
      - 'v*'

env:
  BOOK_SOURCE_DIR: ${{ github.workspace }}/book
  BOOK_BUILD_DIR: ${{ github.workspace }}/build

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: asciidoctor/docker-asciidoctor
      volumes:
        - ${{ github.workspace }}:/documents
    steps:
      - uses: actions/checkout@v4

      - name: "Set filename"
        id: filename
        run: |
          echo "pdf=${{ github.event.repository.name }}-${{ github.ref_name }}.pdf" >> $GITHUB_OUTPUT

      - name: "Build PDF"
        run: |
          GITSHA=$(echo "${{ github.sha }}" | cut -c1-7)
          asciidoctor-pdf \
            -a gitsha=$GITSHA \
            -a pdf-themesdir=$BOOK_SOURCE_DIR/themes \
            -a pdf-theme=basic \
            -a pdf-fontsdir=$BOOK_SOURCE_DIR/fonts \
            -D $BOOK_BUILD_DIR \
            -o ${{ steps.filename.outputs.pdf }} \
            $BOOK_SOURCE_DIR/index.adoc

      - name: "Create Release"
        uses: softprops/action-gh-release@v2
        with:
          files: build/${{ steps.filename.outputs.pdf }}
          generate_release_notes: true
